### ISSUE TITLE
0.0.6 invalid for Alfred 4

### ISSUE THREAD

**Issue by christianbarkowsky** [ThomasTr/Alfred-Symfony-Docs#2]
Cannot import version 0.0.6 to Alfred 4.

<img width="416" alt="Bildschirmfoto 2020-07-22 um 09 54 56" src="https://user-images.githubusercontent.com/1230547/88151349-e14ad480-cc02-11ea-9f55-7a6105bb27c7.png">

**Comment by ThomasTr** [comment]
Hi @christianbarkowsky,
maybe you can try it again? Perhaps remove the old workflow before? Since the last versions the code is basically the same, only cosmetic updates in readme, screenshot and syncing composer.

Reinstalled for me in Alfred 4.1 [1167] and it works.

Awaiting your feedback.

**Comment by christianbarkowsky** [comment]
I removed the workflow. Unfortunately the same message comes!

**Comment by ThomasTr** [comment]
Which version of Alfred do you use?
Can you post contents of console log after install attempt?
Did you took the Symfony-Docs.alfredworkflow file, not the zipfile?

Sorry, but unable to reproduce your issue.

**Comment by christianbarkowsky** [comment]
Alfred 4.1 [1167]

**Comment by christianbarkowsky** [comment]
Fixed via drag n drop. Thx for the tip via telefon. 👍

**Comment by ThomasTr** [comment]
Thanks for your nice phone call: Drag and drop the workflow in the alfred settings pane worked.
